# Generated by Django 3.2.8 on 2021-10-05 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now=True, verbose_name='Дата создания')),
                ('title', models.CharField(max_length=200, verbose_name='Название обьявления')),
                ('description', models.CharField(max_length=1000, verbose_name='Описание')),
                ('img', models.URLField(verbose_name='Изображение')),
                ('additional_img', models.URLField(verbose_name='Доп изображение 1')),
                ('additional_img_2', models.URLField(verbose_name='Доп изображение 2')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
            },
        ),
    ]
