# Generated by Django 3.2.8 on 2021-10-05 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_auto_20211005_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advert',
            name='img',
            field=models.URLField(unique=True, verbose_name='Изображение'),
        ),
    ]
